# Site settings
title: Lucas Seninge
description: "Machine Learning Scientist @ NewLimit"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Latent Space Walk
user_title: LucasESBS
email: lucas.seninge@gmail.com
twitter_username: loremipsum
github_username:  LucasESBS
discord_invite: cj5rg # Example: Discord server invite gg extension like in 'https://discord.gg/cj5rg'
linkedin_public_url: seningelucas # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: loremipsum
profile_picture: https://avatars.githubusercontent.com/u/26789402?s=400&u=ddf1301ec0def0b5c7d2544ef776eb649e44bfbf&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/LucasESBS
      new_tab: true
      key_trigger: g
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: vega, a VAE enhanced by gene annotations
    url: https://github.com/LucasESBS/vega
  - name: louvainpy, Louvain algorithm in Numpy
    url: https://github.com/LucasESBS/louvainpy


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
